### ISSUE TITLE
Old data migration script fails when upgrading from version 1.5.0 to 1.6.0

### ISSUE THREAD

**Issue by damirdean** [Rhetos/LightDMS#2]
FrameworkException: SqlException has occurred in 'Rhetos.LightDMS\002 - ExternalEntityID rename.sql':

Msg 2601, Level 14, State 1, Line 2

Cannot insert duplicate key row in object 'LightDMS.DocumentVersion' with unique index 'IX_DocumentVersion_DocumentID_VersionNumber'. The duplicate key value is (<NULL>, 1).

**Comment by bantolov** [comment]
The bug seem to exist since v1.2 or earlier (it's included in the first commit on this repos), but is usually triggered by issue Rhetos/Rhetos#80 after **upgrading from LightDms 1.4.0 or 1.5.0**.

It will be fixed in LightDms 1.7.0.
